# Generated by Django 4.2.5 on 2023-09-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="posted_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="transferhistory",
            name="posting_date",
            field=models.DateTimeField(),
        ),
    ]
