# Generated by Django 4.2.5 on 2023-09-07 00:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_branch_posted_date_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="branch",
            managers=[
                ("orm", django.db.models.manager.Manager()),
            ],
        ),
    ]
